// Generated by info.scce.cinco.product.userdocumentation.codegen.SeleniumScriptGenerator
package info.scce.cinco.product.userdoc;

import java.io.File;
import java.time.Duration;
import java.io.IOException;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.OutputType;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import static org.openqa.selenium.support.ui.ExpectedConditions.presenceOfElementLocated;

/**
 * This class is the main entry point of the model-based generated application.
 * Whenever you make some changes to your model and click generate, this class will be
 * automatically regenerated.
 * 
 * It is discouraged to edit this class, since any changes made will be overwritten.
 *
 * @author Mukendi Mputu
 */

@SuppressWarnings("unused")
class GetSeleniumScreenshots implements Runnable{
	// User Credentials
	private static String username;
	private static String password;
	private static String email;
	private static WebDriver firefoxDriver;
	private static WebDriverWait wait;
	// No Selenium Property were specified
	private static WebElement element;
	private static Long DEFAULT_TIMEOUT = 10L;

	private GetSeleniumScreenshots() {
		username = "";
		email = "";
		password = "";
		System.setProperty("webdriver.gecko.driver", "/home/mukendi/opt/WebDriver/bin/geckodriver");
		firefoxDriver = new FirefoxDriver();
		wait = new WebDriverWait(firefoxDriver, Duration.ofSeconds(DEFAULT_TIMEOUT));
		element = null;
	}

	public static void main(String[] args) {
		GetSeleniumScreenshots app = new GetSeleniumScreenshots();
		app.run();
	}

	@Override
	public void run() {
		// For every feature container in the MGL generate a sequence of methods
		this.openBrowser();
		{
			// Start of sequence Create New List
			try {
				// DocNode CreateNewList
				this.goToPage("http://localhost:8080");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div")));
				this.takePageScreenshot("CreateNewList", "ApplicationLandingPage");
				this.highlightElement("#username"); 
				this.typeIn("#username", "peter");
				this.highlightElement("#password"); 
				this.typeIn("#password", "pwd");
				this.highlightElement("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button"); 
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button")));
				this.takePageScreenshot("CreateNewList", "ApplicationLandingPage");
				this.highlightElement("input.form-control[placeholder='e.g. Shopping']");
				this.typeIn("input.form-control[placeholder='e.g. Shopping']", "Shopping");
				wait.until(presenceOfElementLocated(By.cssSelector("")));
				this.takePageScreenshot("CreateNewList", "EnterListName");
				this.clickBtn("button[aria-label='Add List']");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > home-aycj5qmwmeewzvvvwxpyu8a-process > home-tag > div > div > div > dime-panel > div")));
				this.takePageScreenshot("CreateNewList", "ListCreated");
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
			// Reset the application state
			}
		}
		{
			// Start of sequence Add List Entry
			try {
				// DocNode AddListEntry
				this.goToPage("http://localhost:8080");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div")));
				this.takePageScreenshot("AddListEntry", "ApplicationLandingPage");
				this.highlightElement("#username"); 
				this.typeIn("#username", "peter");
				this.highlightElement("#password"); 
				this.typeIn("#password", "pwd");
				this.highlightElement("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button"); 
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button")));
				this.takePageScreenshot("AddListEntry", "ApplicationLandingPage");
				this.typeIn("input.form-control[placeholder='e.g. Shopping']", "Shopping");
				this.clickBtn("button[aria-label='Add List']");
				wait.until(presenceOfElementLocated(By.cssSelector("input[placeholder=\"e.g. grab some apples\"]")));
				this.highlightElement("input[placeholder=\"e.g. grab some apples\"]");
				this.typeIn("input[placeholder=\"e.g. grab some apples\"]", "return t-shirt");
				this.takePageScreenshot("AddListEntry", "AddlistEntry");
				this.clickBtn("button[aria-label='Add TODO']");
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
			// Reset the application state
			}
		}
		{
			// Start of sequence Add List Owner
			try {
				// DocNode AddListOwner
				this.goToPage("http://localhost:8080");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div")));
				this.takePageScreenshot("AddListOwner", "ApplicationLandingPage");
				this.highlightElement("#username"); 
				this.typeIn("#username", "peter");
				this.highlightElement("#password"); 
				this.typeIn("#password", "pwd");
				this.highlightElement("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button"); 
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button")));
				this.takePageScreenshot("AddListOwner", "ApplicationLandingPage");
				this.typeIn("input.form-control[placeholder='e.g. Shopping']", "Shopping");
				this.clickBtn("button[aria-label='Add List']");
				this.highlightElement("select.form-control");
				this.highlightElement("select.form-control"); 
				this.select("select.form-control", "Mary Jane");
				wait.until(presenceOfElementLocated(By.cssSelector("table[class=\"table table-striped table-hover table-condensed\"] > tbody > tr")));
				this.takePageScreenshot("AddListOwner", "Addinglistowner");
				this.clickBtn("button[aria-label=\"Add Owner\"]");
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
			// Reset the application state
			}
		}
		{
			// Start of sequence Remove List Owner
			try {
				// DocNode RemoveListOwner
				this.goToPage("http://localhost:8080");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div")));
				this.takePageScreenshot("RemoveListOwner", "ApplicationLandingPage");
				this.highlightElement("#username"); 
				this.typeIn("#username", "peter");
				this.highlightElement("#password"); 
				this.typeIn("#password", "pwd");
				this.highlightElement("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button"); 
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button")));
				this.takePageScreenshot("RemoveListOwner", "ApplicationLandingPage");
				this.typeIn("input.form-control[placeholder='e.g. Shopping']", "Shopping");
				this.clickBtn("button[aria-label='Add List']");
				this.select("select.form-control", "Mary Jane");
				this.clickBtn("button[aria-label=\"Add Owner\"]");
				wait.until(presenceOfElementLocated(By.cssSelector("table[class=\"table table-striped table-hover table-condensed\"] > tbody > tr")));
				this.highlightElement("button[aria-label=\"Remove Owner\"]");
				this.takePageScreenshot("RemoveListOwner", "removinglistowner");
				this.clickBtn("button[aria-label=\"Remove Owner\"]");
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
			// Reset the application state
			}
		}
		{
			// Start of sequence Delete List Entry
			try {
				// DocNode DeleteListEntry
				this.goToPage("http://localhost:8080");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div")));
				this.takePageScreenshot("DeleteListEntry", "ApplicationLandingPage");
				this.highlightElement("#username"); 
				this.typeIn("#username", "peter");
				this.highlightElement("#password"); 
				this.typeIn("#password", "pwd");
				this.highlightElement("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button"); 
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button")));
				this.takePageScreenshot("DeleteListEntry", "ApplicationLandingPage");
				this.typeIn("input.form-control[placeholder='e.g. Shopping']", "Shopping");
				this.clickBtn("button[aria-label='Add List']");
				this.typeIn("input[placeholder=\"e.g. grab some apples\"]", "return t-shirt");
				this.clickBtn("button[aria-label='Add TODO']");
				this.highlightElement("table[id^=table] > tbody > tr"); 
				wait.until(presenceOfElementLocated(By.cssSelector("table[class=\"table table-striped table-hover table-condensed\"] > tbody > tr")));
				this.takePageScreenshot("DeleteListEntry", "removinglistentry");
				this.clickBtn("button[aria-label='Delete TODO']");
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
			// Reset the application state
			}
		}
		{
			// Start of sequence Delete List
			try {
				// DocNode DeleteList
				this.goToPage("http://localhost:8080");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div")));
				this.takePageScreenshot("DeleteList", "ApplicationLandingPage");
				this.highlightElement("#username"); 
				this.typeIn("#username", "peter");
				this.highlightElement("#password"); 
				this.typeIn("#password", "pwd");
				this.highlightElement("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button"); 
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button")));
				this.takePageScreenshot("DeleteList", "ApplicationLandingPage");
				this.typeIn("input.form-control[placeholder='e.g. Shopping']", "Shopping");
				this.clickBtn("button[aria-label='Add List']");
				this.highlightElement("div[aria-label='button group']"); 
				this.takePageScreenshot("DeleteList", "ListSectionhighlighted_");
				this.clickBtn("button[aria-label='Remove']");
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
			// Reset the application state
			}
		}
		{
			// Start of sequence Login
			try {
				// DocNode UserLogin
				this.goToPage("http://localhost:8080");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div")));
				this.takePageScreenshot("Login", "ApplicationLandingPage");
				this.highlightElement("#username"); 
				this.typeIn("#username", "peter");
				this.highlightElement("#password"); 
				this.typeIn("#password", "pwd");
				this.highlightElement("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button"); 
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
				wait.until(presenceOfElementLocated(By.cssSelector("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button")));
				this.takePageScreenshot("Login", "ApplicationLandingPage");
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
			// Reset the application state
			}
		}
		this.closeBrowser();
	}

	/*================== Selenium Methods ==================*/

	public Boolean openBrowser()
	{
		GetSeleniumScreenshots.firefoxDriver.manage().window().maximize();
		return true;
	}
	public Boolean goToPage(String sSiteURL)
	{
		GetSeleniumScreenshots.firefoxDriver.get(sSiteURL);
		return true;
	}
	public Boolean takePageScreenshot(String folderName, String pictureName) throws IOException
	{
		try {
	        Thread.sleep(1000);
	    } catch (InterruptedException e) {
	        e.printStackTrace();
	    }
		//Use TakesScreenshot method to capture screenshot
		TakesScreenshot screenshot = (TakesScreenshot)GetSeleniumScreenshots.firefoxDriver;
		File source = screenshot.getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(source, new File("documentation/docs/src/features/"+folderName+"/" + pictureName + ".png"));
		return true;
	}
	public WebElement findPageElement(String selector)
	{
		return GetSeleniumScreenshots.firefoxDriver.findElement(By.cssSelector(selector));
	}
	public void highlightElement(String selector)
	{
		JavascriptExecutor jsExec = (JavascriptExecutor)GetSeleniumScreenshots.firefoxDriver;
		jsExec.executeScript("arguments[0].setAttribute('style','border: 4px solid red;');", findPageElement(selector));
	}
	public void undoHighlightElement(String selector)
	{
		JavascriptExecutor jsExec = (JavascriptExecutor)GetSeleniumScreenshots.firefoxDriver;
		jsExec.executeScript("arguments[0].setAttribute('style','border: 4px solid red;');", findPageElement(selector));
	}
	public Boolean typeIn(String selector, String contentText)
	{
		findPageElement(selector);
		return true;
	}
	public Boolean clickBtn(String selector)
	{
		findPageElement(selector).click();
		return true;
	}
	public Boolean select(String selector, String option)
	{
		Select selectBox = new Select(findPageElement(selector));
		selectBox.selectByVisibleText(option);
		return true;
	}
	public Boolean pressEnter()
	{
		findPageElement("button[type='submit']").click();
		return true;
	}
	public void closeBrowser()
	{
		GetSeleniumScreenshots.firefoxDriver.close();
	}
}
