// Generated by info.scce.cinco.product.userdocumentation.codegen.SeleniumScriptGenerator
package info.scce.cinco.product.userdoc;

import java.io.File;
import java.time.Duration;
import java.io.IOException;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.OutputType;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import static org.openqa.selenium.support.ui.ExpectedConditions.presenceOfElementLocated;

/**
 * This class is the main entry point of the model-based generated application.
 * Whenever you make some changes to your model and click generate, this class will be
 * automatically regenerated.
 * 
 * It is discouraged to edit this class, since any changes made will be overwritten.
 *
 * @author Mukendi Mputu
 */
class GetSeleniumScreenshots implements Runnable{
	// User Credentials
	private static String username;
	private static String password;
	private static String email;
	private static WebDriver firefoxDriver;
	private static WebDriverWait wait;
	// No Selenium Property were specified
	private static WebElement element;
	private static Long DEFAULT_TIMEOUT = 10L;

	private GetSeleniumScreenshots() {
		username = "";
		email = "";
		password = "";
		System.setProperty("webdriver.gecko.driver", "/home/mukendi/opt/WebDriver/bin/geckodriver");
		firefoxDriver = new FirefoxDriver();
		wait = new WebDriverWait(firefoxDriver, Duration.ofSeconds(DEFAULT_TIMEOUT));
		element = null;
	}

	public static void main(String[] args) {
		GetSeleniumScreenshots app = new GetSeleniumScreenshots();
		app.run();
	}

	@Override
	public void run() {
		// For every feature container in the MGL generate a sequence of methods
		this.openBrowser();
		{
			// Start of sequence Create New List
			try {
				// DocNode CreateNewList
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		{
			// Start of sequence Add List Entry
			try {
				// DocNode AddListEntry
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		{
			// Start of sequence Add List Owner
			try {
				// DocNode AddListOwner
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		{
			// Start of sequence Remove List Owner
			try {
				// DocNode RemoveListOwner
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		{
			// Start of sequence Delete List Entry
			try {
				// DocNode DeleteListEntry
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		{
			// Start of sequence Delete List
			try {
				// DocNode DeleteList
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		{
			// Start of sequence Login
			try {
				// DocNode UserLogin
				this.goToPage("http://localhost:8080");
				this.takePageScreenshot("Login", "ApplicationLandingPage"); 
				this.typeIn("#username", "peter");
				this.typeIn("#password", "pwd");
				this.clickBtn("body > app > routable-aycj5qmwmeewzvvvwxpyu8a-process > root-home-aycj5qmwmeewzvvvwxpyu8a-process > login-form > div > div > div > div > form > div.row > div > button");
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		this.closeBrowser();
	}

	/*================== Selenium Methods ==================*/

	public Boolean openBrowser()
	{
		GetSeleniumScreenshots.firefoxDriver.manage().window().maximize();
		return true;
	}
	public Boolean goToPage(String sSiteURL)
	{
		GetSeleniumScreenshots.firefoxDriver.get(sSiteURL);
		return true;
	}
	public Boolean takePageScreenshot(String folderName, String pictureName) throws IOException
	{
		try {
	        Thread.sleep(1000);
	    } catch (InterruptedException e) {
	        e.printStackTrace();
	    }
		//Use TakesScreenshot method to capture screenshot
		TakesScreenshot screenshot = (TakesScreenshot)GetSeleniumScreenshots.firefoxDriver;
		File source = screenshot.getScreenshotAs(OutputType.FILE);
		FileUtils.copyFile(source, new File("documentation/docs/src/features/"+folderName+"/" + pictureName + ".png"));
		return true;
	}
	public WebElement findPageElement(String selector)
	{
		return GetSeleniumScreenshots.firefoxDriver.findElement(By.cssSelector(selector));
	}
	public void highlightElement(String selector)
	{
		JavascriptExecutor jsExec = (JavascriptExecutor)GetSeleniumScreenshots.firefoxDriver;
		jsExec.executeScript("arguments[0].setAttribute('style','border: 2px solid red;');", findPageElement(selector));
	}
	public Boolean typeIn(String selector, String contentText)
	{
		findPageElement(selector).sendKeys(contentText + Keys.TAB);
		return true;
	}
	public Boolean waitUntilElementPresent(String selector) {
		return wait.until(presenceOfElementLocated(By.cssSelector(selector)))!= null;
	}
	public Boolean clickBtn(String selector)
	{
		findPageElement(selector).click();
		return true;
	}
	public Boolean pressEnter()
	{
		findPageElement("button[type='submit']").click();
		return true;
	}
	public void closeBrowser()
	{
		GetSeleniumScreenshots.firefoxDriver.close();
	}
}
